export const orders =[
    {
        id: 1,
        user: "santillienzo",
        product: "Vino Malbec",
        first_name: "Enzo",
        last_name: "Santilli",
        country: "Argentina",
        direction: "Barrio San Pedro M20 C27",
        location: "San Martín",
        province: "Mendoza",
        postal_code: "M5570",
        phone: "02634786580",
        email: "enzo135246@gmail.com",
        payment_method: "Mercado Pago",
        payment_order: 300,
        payment_status: 0,
        shipping_method: "Andreani",
        shipping_cost: 720
    },
    {
        id: 2,
        user: "santillienzo",
        product: "Vino Malbec",
        first_name: "Enzo",
        last_name: "Santilli",
        country: "Argentina",
        direction: "Barrio San Pedro M20 C27",
        location: "San Martín",
        province: "Mendoza",
        postal_code: "M5570",
        phone: "02634786580",
        email: "enzo135246@gmail.com",
        payment_method: "Mercado Pago",
        payment_order: 300,
        payment_status: 1,
        shipping_method: "Andreani",
        shipping_cost: 720
    },
    {
        id: 3,
        user: "santillienzo",
        product: "Vino Malbec",
        first_name: "Enzo",
        last_name: "Santilli",
        country: "Argentina",
        direction: "Barrio San Pedro M20 C27",
        location: "San Martín",
        province: "Mendoza",
        postal_code: "M5570",
        phone: "02634786580",
        email: "enzo135246@gmail.com",
        payment_method: "Mercado Pago",
        payment_order: 300,
        payment_status: 2,
        shipping_method: "Andreani",
        shipping_cost: 720
    },
]